name: Go CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  GOLANGCI-LINT_VERSION: v2.13
  
permissions:
  contents: read

jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          
      - name: Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI-LINT_VERSION }}
  
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
        
      - name: Tests
        run: |
          go vet -v ./...
          go test -v -race ./...      
        
  build:
    name: Build SMTP
    runs-on: ubuntu-latest
    needs: [ "lint", "test" ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
        
      - name: Build
        run: go build -v ./...
